import { Geist, Geist_Mono, Poppins, Open_Sans , Bricolage_Grotesque, Space_Grotesk} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Space_Grotesk({
    weight: ["300", "400", "500", "600", "700"], // choose weights you need
    subsets: ["latin"],
});

export const metadata = {
  title: "Manohar Kumar | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body
        className={`${poppins.className} antialiased`}
      >
        <ThemeProvider 
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
